version: "3.4"

services:
  mp3player:
    image: mp3player
    build:
      context: client
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      - server
    links:
      - server
    environment:
      REACT_APP_SERVER_URL: http://localhost:8000

  server:
    image: server
    container_name: server
    build:
      context: server
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      NODE_ENV: production
